USE WASTE2MONEYDB;

DELIMITER $$
USE `WASTE2MONEYDB`$$

CREATE PROCEDURE `userAddOrEdit` (
  IN _ID_USUARIO INT,
  IN _USUARIO VARCHAR(30),
  IN _CONTRASEÑA VARCHAR(30),
  IN _CORREO VARCHAR(30)
)
BEGIN 
  IF _ID_USUARIO = 0 THEN
    INSERT INTO TB_USER (USUARIO, CONTRASEÑA, CORREO)
    VALUES (_USUARIO, _CONTRASEÑA, _CORREO);

    SET _ID_USUARIO = LAST_INSERT_ID();
  ELSE
    UPDATE TB_USER
    SET
    USUARIO = _USUARIO,
    CONTRASEÑA = _CONTRASEÑA,
    CORREO = _CORREO
    WHERE ID_USUARIO = _ID_USUARIO;
  END IF;

  SELECT _ID_USUARIO AS 'id';
END