
CREATE DATABASE IF NOT EXISTS WASTE2MONEYDB;

USE WASTE2MONEYDB;

CREATE TABLE TB_USER(
ID_USUARIO INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
USUARIO NVARCHAR(30) NOT NULL,
CONTRASEÑA NVARCHAR(30) NOT NULL,
CORREO NVARCHAR(30) NOT NULL
);

CREATE TABLE TB_SCORE(
ID_SCORE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
PUNTUACION NVARCHAR(10) NOT NULL
);


CREATE TABLE TB_CLIENTE (
    ID_CLIENTE INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOMBRE NVARCHAR(50) NOT NULL,
    TELEFONO NVARCHAR(10) NOT NULL,
    DIRECCION NVARCHAR(50) NOT NULL,
    ID_USUARIO INT NOT NULL,
    ID_SCORE INT NOT NULL,
    CONSTRAINT fk_Cliente_User FOREIGN KEY (ID_USUARIO)
        REFERENCES TB_USER (ID_USUARIO),
    CONSTRAINT fk_Score FOREIGN KEY (ID_SCORE)
        REFERENCES TB_SCORE (ID_SCORE)
);

CREATE TABLE TB_ADMIN(
ID_ADMIN INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
NOMBRE NVARCHAR(50) NOT NULL,
TELEFONO NVARCHAR(10) NOT NULL,
ID_USUARIO INT NOT NULL,

CONSTRAINT fk_Administrador_User FOREIGN KEY (ID_USUARIO) REFERENCES TB_USER(ID_USUARIO)
);



